FROM golang:1.11.5-alpine as builder

WORKDIR ${GOPATH}/src/github.com/ngalayko/p2p

COPY . .

RUN go build -o /dispatcher ./cmd/dispatcher/main.go

FROM alpine:3.9

COPY --from=builder /dispatcher /dispatcher

ENTRYPOINT [ "/dispatcher" ]
