FROM golang:1.11.5-alpine as builder

ARG GOOS=linux
ARG GOARCH=arm

WORKDIR ${GOPATH}/src/github.com/ngalayko/p2p

COPY . .

RUN GOOS=${GOOS} GOARCH=${GOARCH} go build -o /dispatcher ./cmd/dispatcher/main.go

#FROM scratch
FROM alpine:3.8

COPY --from=builder /dispatcher /dispatcher

ENTRYPOINT [ "/dispatcher" ]
