FROM golang:1.11.5-alpine as builder

ARG GOOS=linux
ARG GOARCH=arm

WORKDIR ${GOPATH}/src/github.com/ngalayko/p2p

COPY . .

RUN GOOS=${GOOS} GOARCH=${GOARCH} go build -o /peer ./cmd/peer/main.go

COPY ./client/public /public

#FROM scratch
FROM alpine:3.8

COPY --from=builder /peer /peer
COPY --from=builder /public /public

ENTRYPOINT [ "/peer", "--static_path=/public" ]
