FROM golang:1.11.5-alpine as builder

ARG GOOS=linux
ARG GOARCH=arm

WORKDIR ${GOPATH}/src/github.com/ngalayko/p2p

COPY . .

RUN GOOS=${GOOS} GOARCH=${GOARCH} go build -o /dispatcher ./cmd/dispatcher/main.go

COPY ./dispatcher/public /public

FROM scratch

COPY --from=builder /dispatcher /dispatcher
COPY --from=builder /public /public

ENTRYPOINT [ "/dispatcher", "--staticPath=/public" ]
