// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageStatusStatus int32

const (
	MessageStatus_INVALID   MessageStatusStatus = 0
	MessageStatus_DELIVERED MessageStatusStatus = 1
	MessageStatus_READ      MessageStatusStatus = 2
)

var MessageStatusStatus_name = map[int32]string{
	0: "INVALID",
	1: "DELIVERED",
	2: "READ",
}

var MessageStatusStatus_value = map[string]int32{
	"INVALID":   0,
	"DELIVERED": 1,
	"READ":      2,
}

func (x MessageStatusStatus) String() string {
	return proto.EnumName(MessageStatusStatus_name, int32(x))
}

func (MessageStatusStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1, 0}
}

type Message struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id        string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_Text
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Text struct {
	Text string `protobuf:"bytes,5,opt,name=text,proto3,oneof"`
}

func (*Message_Text) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetText() string {
	if x, ok := m.GetPayload().(*Message_Text); ok {
		return x.Text
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Text)(nil),
	}
}

type MessageStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageStatus) Reset()         { *m = MessageStatus{} }
func (m *MessageStatus) String() string { return proto.CompactTextString(m) }
func (*MessageStatus) ProtoMessage()    {}
func (*MessageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *MessageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStatus.Unmarshal(m, b)
}
func (m *MessageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStatus.Marshal(b, m, deterministic)
}
func (m *MessageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStatus.Merge(m, src)
}
func (m *MessageStatus) XXX_Size() int {
	return xxx_messageInfo_MessageStatus.Size(m)
}
func (m *MessageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStatus proto.InternalMessageInfo

func (m *MessageStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("chat.MessageStatusStatus", MessageStatusStatus_name, MessageStatusStatus_value)
	proto.RegisterType((*Message)(nil), "chat.Message")
	proto.RegisterType((*MessageStatus)(nil), "chat.MessageStatus")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcd, 0x4b, 0xc3, 0x30,
	0x14, 0x6f, 0x4a, 0x6d, 0xed, 0x1b, 0x95, 0x12, 0x3d, 0x94, 0x5e, 0x1c, 0x3d, 0xf5, 0x94, 0x49,
	0xbd, 0x88, 0xb7, 0x69, 0x0b, 0x16, 0xa6, 0x42, 0x26, 0xbb, 0xbf, 0xd9, 0xd8, 0x15, 0x56, 0x52,
	0x96, 0x37, 0xd0, 0xff, 0x5e, 0xd6, 0x0f, 0x65, 0xb7, 0xfc, 0xbe, 0xc9, 0x03, 0xf8, 0xdc, 0x21,
	0x89, 0xee, 0xa0, 0x49, 0x73, 0xe7, 0xf4, 0x8e, 0x6f, 0x6b, 0xad, 0xeb, 0xbd, 0x5a, 0xf4, 0xdc,
	0xf6, 0xf8, 0xb5, 0xa0, 0xa6, 0x55, 0x86, 0xb0, 0xed, 0x06, 0x5b, 0x42, 0xe0, 0xbd, 0x2a, 0x63,
	0xb0, 0x56, 0xfc, 0x01, 0xfc, 0x3f, 0x35, 0x62, 0x73, 0x96, 0xce, 0xb2, 0x58, 0x0c, 0x79, 0x31,
	0xe5, 0xc5, 0xc7, 0xe4, 0x90, 0xff, 0x66, 0x7e, 0x05, 0x76, 0x53, 0x45, 0xf6, 0x9c, 0xa5, 0xbe,
	0xb4, 0x9b, 0x8a, 0xdf, 0x80, 0x43, 0xea, 0x9b, 0xa2, 0x8b, 0x13, 0xf3, 0x62, 0xc9, 0x1e, 0x3d,
	0xf9, 0xe0, 0x75, 0xf8, 0xb3, 0xd7, 0x58, 0x25, 0xef, 0x10, 0x8c, 0xab, 0x6b, 0x42, 0x3a, 0x9a,
	0xb1, 0x81, 0x4d, 0x0d, 0x89, 0x00, 0xd7, 0x0c, 0xca, 0x0c, 0xbc, 0xf2, 0x6d, 0xb3, 0x5c, 0x95,
	0x79, 0x68, 0xf1, 0x00, 0xfc, 0xbc, 0x58, 0x95, 0x9b, 0x42, 0x16, 0x79, 0xc8, 0xf8, 0x25, 0x38,
	0xb2, 0x58, 0xe6, 0xa1, 0x9d, 0x3d, 0x82, 0xf3, 0xbc, 0x43, 0xe2, 0x19, 0xb8, 0x6b, 0x3a, 0x28,
	0x6c, 0x79, 0x20, 0xfa, 0x63, 0x8c, 0x33, 0xf1, 0xf5, 0x19, 0x1c, 0x56, 0x13, 0x2b, 0x65, 0x77,
	0x6c, 0xeb, 0xf6, 0x9f, 0xbb, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xc4, 0x12, 0x72, 0x3e,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Chat_StreamClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Chat_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/chat.Chat/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatStreamClient{stream}
	return x, nil
}

type Chat_StreamClient interface {
	Send(*Message) error
	Recv() (*MessageStatus, error)
	grpc.ClientStream
}

type chatStreamClient struct {
	grpc.ClientStream
}

func (x *chatStreamClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatStreamClient) Recv() (*MessageStatus, error) {
	m := new(MessageStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Stream(Chat_StreamServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Stream(&chatStreamServer{stream})
}

type Chat_StreamServer interface {
	Send(*MessageStatus) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatStreamServer struct {
	grpc.ServerStream
}

func (x *chatStreamServer) Send(m *MessageStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatStreamServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Chat_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
